DROP TABLE IF EXISTS Subscribe;
DROP TABLE IF EXISTS Post;
DROP TABLE IF EXISTS Thread;
DROP TABLE IF EXISTS Forum;
DROP TABLE IF EXISTS Follower;
DROP TABLE IF EXISTS User;

CREATE TABLE User (
	About VARCHAR (5120) NOT NULL,
	Email VARCHAR (255) NOT NULL UNIQUE,
	Id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT UNIQUE,
	IsAnonymous BOOLEAN NOT NULL,
	Name VARCHAR (255) NOT NULL,
	Username VARCHAR (255) NOT NULL
);

CREATE TABLE Follower (
	Follower VARCHAR (255) NOT NULL,
	Followee VARCHAR (255) NOT NULL,
	FOREIGN KEY (Follower) REFERENCES User (Email),
	FOREIGN KEY (Follower) REFERENCES User (Email),
	CONSTRAINT UniqueConstraint UNIQUE (Follower, Followee),
	INDEX FolloweeFollower USING BTREE (Followee, Follower)
);

CREATE TABLE Forum (
	Id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT UNIQUE,
	Name VARCHAR (255) NOT NULL UNIQUE,
	ShortName VARCHAR (255) NOT NULL UNIQUE,
	User VARCHAR (255) NOT NULL,
	FOREIGN KEY (User) REFERENCES User (Email)
);

CREATE TABLE Thread (
	Date DATETIME NOT NULL,
	Dislikes INTEGER NOT NULL,
	Forum VARCHAR (255) NOT NULL,
	Id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT UNIQUE,
	IsClosed BOOLEAN NOT NULL,
	IsDeleted BOOLEAN NOT NULL,
	Likes INTEGER NOT NULL,
	Message VARCHAR (5120) NOT NULL,
	Slug VARCHAR (255) NOT NULL,
	Title VARCHAR (255) NOT NULL,
	User VARCHAR (255) NOT NULL,
	FOREIGN KEY (Forum) REFERENCES Forum (ShortName),
	FOREIGN KEY (User) REFERENCES User (Email),
	INDEX IsDeletedId USING BTREE (IsDeleted, Id)
);

CREATE TABLE Post (
	Date DATETIME NOT NULL,
	Dislikes INTEGER NOT NULL,
	Forum VARCHAR (255) NOT NULL,
	Id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT UNIQUE,
	IsApproved BOOLEAN NOT NULL,
	IsEdited BOOLEAN NOT NULL,
	IsDeleted BOOLEAN NOT NULL,
	IsHighlighted BOOLEAN NOT NULL,
	IsSpam BOOLEAN NOT NULL,
	Likes INTEGER NOT NULL,
	Message VARCHAR (20480) NOT NULL,
	Parent INTEGER NULL,
	Thread INTEGER NOT NULL,
	User VARCHAR (255) NOT NULL,
	Path VARCHAR (255) NULL,
	FOREIGN KEY (Forum) REFERENCES Forum (ShortName),
	FOREIGN KEY (Thread) REFERENCES Thread (Id),
	FOREIGN KEY (User) REFERENCES User (Email),
	INDEX IsDeletedId USING BTREE (IsDeleted, Id)	
);

CREATE TABLE Subscribe (
	User VARCHAR (255) NOT NULL,
	Thread INTEGER NOT NULL,
	FOREIGN KEY (User) REFERENCES User (Email),
	FOREIGN KEY (Thread) REFERENCES Thread (id),
	CONSTRAINT UniqueConstraint UNIQUE (User, Thread),
	INDEX ThreadUser USING BTREE (Thread, User)
);